### ISSUE TITLE
subscription payment error

### ISSUE THREAD

**Issue by Ck-Joker** [j7-dev/woomp#55]
![image](https://github.com/j7-dev/woomp/assets/132816301/47c3cc29-585b-41f0-af10-9b60c9d6bb9c)

error log

2024-06-30T03:14:03+00:00 錯誤 scheduled action 166106 (subscription payment) failed to finish processing due to the following exception: Call to undefined function wc_add_notice() in /home/theunlimitedstudio/htdocs/example.com/wp-content/plugins/woomp/includes/payuni/src/gateways/Response.php:94 CONTEXT: {"action_args":"subscription_id: 6355","error_trace":"#0 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woomp\/includes\/payuni\/src\/gateways\/Request.php(193): PAYUNI\\Gateways\\Response::card_response()\n#1 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woomp\/includes\/payuni\/src\/gateways\/Request.php(247): PAYUNI\\Gateways\\Request->set_response()\n#2 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woomp\/includes\/payuni\/src\/gateways\/Subscription.php(57): PAYUNI\\Gateways\\Request->build_subscription_request()\n#3 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(324): PAYUNI\\Gateways\\Subscription->process_subscription_payment()\n#4 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#5 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#6 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woocommerce-subscriptions\/includes\/gateways\/class-wc-subscriptions-payment-gateways.php(118): do_action()\n#7 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woocommerce-subscriptions\/includes\/gateways\/class-wc-subscriptions-payment-gateways.php(93): WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook()\n#8 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(324): WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment()\n#9 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#10 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/plugin.php(565): WP_Hook->do_action()\n#11 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/actions\/ActionScheduler_Action.php(56): do_action_ref_array()\n#12 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/abstracts\/ActionScheduler_Abstract_QueueRunner.php(88): ActionScheduler_Action->execute()\n#13 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/ActionScheduler_QueueRunner.php(169): ActionScheduler_Abstract_QueueRunner->process_action()\n#14 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/ActionScheduler_QueueRunner.php(139): ActionScheduler_QueueRunner->do_batch()\n#15 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(324): ActionScheduler_QueueRunner->run()\n#16 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#17 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/plugin.php(565): WP_Hook->do_action()\n#18 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-cron.php(191): do_action_ref_array()\n#19 {main}"}
2024-06-30T04:50:02+00:00 錯誤 scheduled action 165932 (subscription payment) failed to finish processing due to the following exception: Call to undefined function wc_add_notice() in /home/theunlimitedstudio/htdocs/example.com/wp-content/plugins/woomp/includes/payuni/src/gateways/Response.php:94 CONTEXT: {"action_args":"subscription_id: 12304","error_trace":"#0 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woomp\/includes\/payuni\/src\/gateways\/Request.php(193): PAYUNI\\Gateways\\Response::card_response()\n#1 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woomp\/includes\/payuni\/src\/gateways\/Request.php(247): PAYUNI\\Gateways\\Request->set_response()\n#2 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woomp\/includes\/payuni\/src\/gateways\/Subscription.php(57): PAYUNI\\Gateways\\Request->build_subscription_request()\n#3 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(324): PAYUNI\\Gateways\\Subscription->process_subscription_payment()\n#4 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#5 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/plugin.php(517): WP_Hook->do_action()\n#6 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woocommerce-subscriptions\/includes\/gateways\/class-wc-subscriptions-payment-gateways.php(118): do_action()\n#7 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/woocommerce-subscriptions\/includes\/gateways\/class-wc-subscriptions-payment-gateways.php(93): WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook()\n#8 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(324): WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment()\n#9 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#10 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/plugin.php(565): WP_Hook->do_action()\n#11 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/actions\/ActionScheduler_Action.php(56): do_action_ref_array()\n#12 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/abstracts\/ActionScheduler_Abstract_QueueRunner.php(88): ActionScheduler_Action->execute()\n#13 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/ActionScheduler_QueueRunner.php(169): ActionScheduler_Abstract_QueueRunner->process_action()\n#14 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-content\/plugins\/seo-by-rank-math\/vendor\/woocommerce\/action-scheduler\/classes\/ActionScheduler_QueueRunner.php(139): ActionScheduler_QueueRunner->do_batch()\n#15 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(324): ActionScheduler_QueueRunner->run()\n#16 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/class-wp-hook.php(348): WP_Hook->apply_filters()\n#17 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-includes\/plugin.php(565): WP_Hook->do_action()\n#18 \/home\/theunlimitedstudio\/htdocs\/example.com\/wp-cron.php(191): do_action_ref_array()\n#19 {main}"}

**Comment by j7-dev** [comment]
![圖片](https://github.com/user-attachments/assets/91f97174-ce9e-4a41-b7d6-c9eb6d276850)
